version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
shallow_clone: true
build:
  verbosity: minimal
only_commits:
  files:
    - docker/
services:
- docker
test_script:
- cd docker
- docker build -t .