version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Ubuntu
shallow_clone: true
build:
  verbosity: minimal
only_commits:
  files:
    - docker/
services:
- docker
test_script:
- cd docker/alpine
- docker build -t jojees/alpine:3.10.2 .