version: 1.0.{build}
branches:
  only:
  - master
environment:
  matrix:
  - TOXENV: py37
skip_tags: true
image: Ubuntu1804
shallow_clone: true
build:
  verbosity: minimal
only_commits:
  files:
    - docker/
skip_commits:
  files:
    - docker/**/.dockerignore
services:
- docker
test_script:
- make docker